update to resolve UnboundLocalError
File "/mi-instrument/mi/core/instrument/playback.py", line 381, in main
    if zplsc_reader:
UnboundLocalError: local variable 'zplsc_reader' referenced before assignment